# Koan medium 

標準ライブラリをインポートして解いていく問題．まずは，
+ [テキスト処理サービス](https://docs.python.org/ja/3/library/text.html)
+ [データ型 ](https://docs.python.org/ja/3/library/datatypes.html)
+ [ファイルとディレクトリへのアクセス ](https://docs.python.org/ja/3/library/filesys.html)
からの出題です．

+ 2019/11/04 Updated (しんせいたろう）

## テキスト処理

In [0]:
 # {} で区切られた置換フィールドを使って、"Hello Sam!" を出力してください
 # 参照： https://docs.python.org/ja/3/library/stdtypes.html#str.format
name = "Sam"

In [0]:
# 同様に、{} で区切られた置換フィールドを使って、"Hello Sam, Dom, and Bom!" を出力してください
names = ("Sam", "Dom", "Bom")

In [0]:
# 辞書で与えられた変数を使って、"Hello Sam, Dom, and Bom!"を出力してください
d = {"a": "Sam", "b": "Dom", "c": "Bom"}

In [0]:
# 下の fmt が与えられている時、"Hello Sam, Dom, and Bom!"を出力してください。
fmt = "Hello {x}, {y} and {z}"

In [0]:
# これは難しいです。
# 「今日の日経平均株価は、-0.33%の22,850.77円です。」と出力してください。ただし下記の変数を使うこと。
ratio = -0.0033333
price = 22850.7710

## 正規表現

python の正規表現は，`re` モジュールをインポートして使います．
+ 公式ドキュメント： [re --- 正規表現操作 — Python 3.8.0 ドキュメント](https://docs.python.org/ja/3/library/re.html)

全部を覚える必要は全くありません．こんな感じかな？というところまで分かっておけば，あとは必要なときに調べ直す，という感じで問題ないです．

今回は，ココで紹介されているものを中心にKoanを書きます
+ [Pythonの正規表現モジュールreの使い方（match、search、subなど）](https://note.nkmk.me/python-re-match-search-findall-etc/)

以下のテーブルは，正規表現を書くときに便利なので載せておきます．
+ 参照：[書きながら覚える！Pythonで正規表現を使う方法【初心者向け】](https://techacademy.jp/magazine/15635)

**メタ文字**

メタ文字|説明|指定例|合致する
---|---|---|---
.|任意の一文字|a.c|abc, acc, aac
^|行の先頭|^abc|abcdef
$|行の末尾|abc$|defabc
*|0回以上の繰り返し|ab*|a, ab, abb, abbb
+|1回以上の繰り返し|ab+|ab, abb, abbb
?|0回または1回|ab?|a, ab
{m}|m回の繰り返し|a{3}|aaa
{m,n}|m〜n回の繰り返し|a{2, 4}|aa, aaa, aaaa
[★]|★のどれか1文字|[a-c]|a, b, c
★|★|★のどれか|a|b|a, b


**特殊シーケンス**

特殊シーケンス|説明|同じ意味の正規表現
---|---|---
\d|任意の数字|[0-9]
\D|任意の数字以外|[^0-9]
\s|任意の空白文字|[\t\n\r\f\v]
\S|任意の空白文字以外|[^\t\n\r\f\v]
\w|任意の英数字|[a-xA-Z0-9_]
\W|任意の英数字以外|[\a-xA-Z0-9_]
\A|文字列の先頭|^
\Z|文字列の末尾| $

In [0]:
# 先頭が ネコ であるか match メソッドを使って確認する
# 返り値が <_sre.SRE_Match object; span=(0, 2), match='ネコ'> であればOK

s = "ネコ 犬 ぞう mouse ネコ"

In [0]:
# sのぞうを象に書き換えてください。
# 'ネコ 犬 象 mouse ネコ'　が出力されれば正解です。
s = "ネコ 犬 ぞう mouse ネコ"

'ネコ 犬 象 mouse ネコ'

In [0]:
# s に mouse が存在するかを、 re.search をつかって確認してください
# <_sre.SRE_Match object; span=(8, 13), match='mouse'>　が出力されれば正解です

s = "ネコ 犬 ぞう mouse ネコ"

In [0]:
# s から ネコを全部取り出してください。
# ['ネコ', 'ネコ'] が出力されれば正解です。
s = "ネコ 犬 ぞう mouse ネコ"

In [0]:
# emails を / で分割して、email list を作成してください
# このようなリストが出力されれば正解です
# ['dinsull0@is.gd',
#  'mlinkleter1@infoseek.co.jp',
#  'aphilcox2@nytimes.com',
#  'awixey3@google.pl']

emails = 'dinsull0@is.gd/mlinkleter1@infoseek.co.jp/aphilcox2@nytimes.com/awixey3@google.pl'

In [0]:
# s を　数値で分割してください
# ['Uriah', 'Romanetti', 'Staci', 'Claw', 'Latia', 'Allflatt'] が出力されれば正解です。
s = "Uriah123Romanetti09Staci3918Claw000Latia12345Allflatt"

## Datetime 

[datetime --- 基本的な日付型および時間型 — Python 3.8.0 ドキュメント](https://docs.python.org/ja/3/library/datetime.html)

Datetime に関しては、８月のFintalkで行った時系列データのノートをベースに作成しています

In [0]:
# 現在の時刻をdatetime 型で表示
# datetime.datetime(2019, 11, 7, 3, 55, 45, 586698) のような表示であれば正解です。
# 注意：コードを実行しているマシンの現在時刻を表示すればよいので、colabratory を使っているときは、UTC時間が表示されるはずです
# 現在のUTCはこちら https://24timezones.com/taimuzon/utc

In [0]:
# 2019/11/7 をdatetime型で表示
# datetime.datetime(2019, 11, 7, 0, 0) が出力されれば正解です

In [0]:
# dt を xxxx年xx月xx日 という文字列に変換
# 今日の日付でxxxx年xx月xx日 と表示されればOK
dt = datetime.now()

In [0]:
# s を datetime に変換
# datetime.datetime(2019, 11, 7, 0, 0) が出力されれば正解
s = '2019/11/07'

In [0]:
# pandas date_range を使って、2019/1/1 ~ 2019/2/1 の日付リストを作成
# DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
#                ......
#                '2019-01-29', '2019-01-30', '2019-01-31', '2019-02-01'],
#               dtype='datetime64[ns]', freq='D')
# が出力されればOKです。

import pandas as pd

In [0]:
# タイムゾーン
# pytz をインポートしてタイムゾーン情報付きのdatetimeオブジェクトを作りましょう

# Tokyoタイムゾーン情報を持つ、現在時刻オブジェクトを出力
# （実行した時間で）このようなオブジェクトが出力されればOK 
# datetime.datetime(2019, 11, 9, 11, 43, 40, 481771, tzinfo=<DstTzInfo 'Asia/Tokyo' JST+9:00:00 STD>)

In [0]:
# dt1 に Tokyoタイムゾーンを付加する
# datetime.datetime(2019, 1, 1, 0, 0, tzinfo=<DstTzInfo 'Asia/Tokyo' LMT+9:19:00 STD>) で正解
dt1 = datetime.strptime("Jan 1, 2019", "%b %d, %Y")

In [0]:
# dt2 を New York 時間に変更
# datetime.datetime(1999, 12, 31, 9, 41, tzinfo=<DstTzInfo 'America/New_York' EST-1 day, 19:00:00 STD>) でOK
dt2 = datetime(2000,1,1, tzinfo=pytz.timezone("Asia/Tokyo"))