# 文字列



##  文字数を数える関数

```python 
string_length("HelloPython")
# 11 

string_length("こんにちわパイソン")
# 9

```

## 文字列の中の文字数を数えて辞書で返す関数

```python
count_chars("facebook.com")
#{'.': 1, 'a': 1, 'b': 1, 'c': 2, 'e': 1, 'f': 1, 'k': 1, 'm': 1, 'o': 3}

count_charts("あかまきがみあおまきがみきまきがみ")
#{'あ': 2, 'お': 1, 'か': 1, 'が': 3, 'き': 4, 'ま': 3, 'み': 3}

```

## 特定の文字列を差し替える関数

```python 
change("repeat after me", "r", "$")
# '$epeat afte$ me' 

change("we love ruby", "ruby", "python")
# we love python
```

## 特定の文字列で分割する関数

```python 
split("abcdefg", "d")
#  ["abc", "efg"]

split("abcdefjgkdss", "d")
# ['abc', 'efjgk', 'ss']
```

## 文字列からデータを作成

```
id,first_name,last_name,email
1,Ada,McGrale,amcgrale0@livejournal.com
2,Astra,Bullcock,abullcock1@sun.com
3,Domenic,Lippett,dlippett2@sun.com
4,Barbie,Thieme,bthieme3@tiny.cc
5,Ximenez,Isabell,xisabell4@unicef.org
```
このような、一行目はヘッダー、あとの行はデータの文字列を、

```python
[{'email': 'amcgrale0@livejournal.com',
  'first_name': 'Ada',
  'id': '1',
  'last_name': 'McGrale'},
 {'email': 'abullcock1@sun.com',
  'first_name': 'Astra',
  'id': '2',
  'last_name': 'Bullcock'},
 {'email': 'dlippett2@sun.com',
  'first_name': 'Domenic',
  'id': '3',
  'last_name': 'Lippett'},
 {'email': 'bthieme3@tiny.cc',
  'first_name': 'Barbie',
  'id': '4',
  'last_name': 'Thieme'},
 {'email': 'xisabell4@unicef.org',
  'first_name': 'Ximenez',
  'id': '5',
  'last_name': 'Isabell'}]
```
このように、ヘッダーをキーに持つ辞書データのリストに変換してください。

```python
s="""id,first_name,last_name,email
1,Ada,McGrale,amcgrale0@livejournal.com
2,Astra,Bullcock,abullcock1@sun.com
3,Domenic,Lippett,dlippett2@sun.com
4,Barbie,Thieme,bthieme3@tiny.cc
5,Ximenez,Isabell,xisabell4@unicef.org"""

string_to_data(s) 

# [{'email': 'amcgrale0@livejournal.com',
#   'first_name': 'Ada',
#   'id': '1',
#   'last_name': 'McGrale'},
#  {'email': 'abullcock1@sun.com',
#   'first_name': 'Astra',
#   'id': '2',
#   'last_name': 'Bullcock'},
#  {'email': 'dlippett2@sun.com',
#   'first_name': 'Domenic',
#   'id': '3',
#   'last_name': 'Lippett'},
#  {'email': 'bthieme3@tiny.cc',
#   'first_name': 'Barbie',
#   'id': '4',
#   'last_name': 'Thieme'},
#  {'email': 'xisabell4@unicef.org',
#   'first_name': 'Ximenez',
#   'id': '5',
#   'last_name': 'Isabell'}]


s="""first_name,tel,car owned
Dion,41-958-9263,Jeep
Joe,30-348-6500,Nissan
Sibelle,42-177-8432,Dodge"""

string_to_data(s) 

# [{'car': 'Jeep', 'first_name': 'Dion', 'tel': '41-958-9263'},
#  {'car': 'Nissan', 'first_name': 'Joe', 'tel': '30-348-6500'},
#  {'car': 'Dodge', 'first_name': 'Sibelle', 'tel': '42-177-8432'}]
```

## 大文字を小文字に、小文字を小文字に変換

```python 
print(case_exchange("IEX Cloud API"))
print(case_exchange("BuzzFeedJapan"))
print(case_exchange("TypeScript"))
```

```
iex cLOUD api
bUZZfEEDjAPAN
tYPEsCRIPT
```

## 2つの文字列にで共通しない文字だけで文字列を作る

```python
uncommon_strings('123456', '456789')
## 123789

uncommon_strings('日本アメリカ英国', 'アメリカ')
## 日本英国
```

## 空白文字を取り除く

```python 
remove_string("Willie	Kayley	wkayley0@smh.com.au	Female	229.4.97.115")
# WillieKayleywkayley0@smh.com.auFemale229.4.97.115

remove_string("Willie\nKayley\swkayley0@smh.com.au	Female	229.4.97.115")
# WillieKayleywkayley0@smh.com.auFemale229.4.97.115

remove_string("  Willie	Kayley	wkayley0@smh.com.au	Female	229.4.97.115  ")
# WillieKayleywkayley0@smh.com.auFemale229.4.97.115

```

## 連続した文字列を取り除く

hint: itertools を使う

```python 
remove_duplicates_strings("112344568557236")
# 123456857236

remove_duplicates_strings("booktooluuum")
# boktolum
```

## 【⭐】現在時刻を持つファイル名を作成 

以下のフォーマットで**現在日時**のファイルパスを作成して下さい。

1. `yyyy-mm-dd.csv` （例：2020-07-06.csv）
1. `yyyymmdd-HHMM.txt` (例：20200706-1354.txt) 
1. `/home/<yourname>/YYYY/yyyymmdd.html` (例：/home/shinseitaro/2020/20200706.html)

## 【⭐】URLを作る1

```python 
base_url = "example.com"
generate_urls(base_url, range(1,10))

# ['example.com/page/1',
#  'example.com/page/2',
#  'example.com/page/3',
#  'example.com/page/4',
#  'example.com/page/5',
#  'example.com/page/6',
#  'example.com/page/7',
#  'example.com/page/8',
#  'example.com/page/9']
```

## 【⭐】URLを作る2

ランダムな文字列を含むURLをｎ個作成する。その時
+ ランダムな文字列は、英数字（小文字大文字含む）を k 個
とする

```python
base_url = "example.com"
n = 10
k = 20
generate_urls_with_randomletters(base_url, n, k)

# ['example.com/page/l7WqGATEmnkMGYWu4WPL',
#  'example.com/page/FdOryIxra0IDGHr2p0mK',
#  'example.com/page/FLiPFYfajcdrkFPmlWJU',
#  'example.com/page/0n37pYizG5yKDTV6DD1g',
#  'example.com/page/VCuMfN2OJH9HRCGQME6a',
#  'example.com/page/vQbbUofIssIupEEhCeM4',
#  'example.com/page/uIkil0UWD05BiU0pq0uM',
#  'example.com/page/kTF4I7YaZRRVqWr3noPR',
#  'example.com/page/YI6IiLcfODxBJvcv0yxi']

```

## 【⭐】フォーマット

```csv
company name,revenue,stock price 
Orelie,$1.64B,50.406
Haleigh,$2.17B,83.541
Mikaela,$6.06B,51.754
Minna,$618.48M,55.853
Hermine,$192.01M,65.51
Borden,$8M,60.212
Cart,n/a,79.988
Kittie,$1.04B,73.679
Cassey,$2.97B,86.23
Alejandra,$2.92B,56.938
```

上記をデータをヘッダーをKey、各行をValueにもつ辞書のリストに変換して下さい。ただし、
+ company nameは
    + 大文字に変換
+ revenueは、
    + 通貨記号は削除
    + B: billion = 10億 で数値変換
    + M: millon = 100万 で数値変換
    + n/a: は numpy nan に変換
+ stock priceは
    + 小数点1位まで（四捨五入）

よって、このようなデータを作成して下さい。
```
[{'company name': 'ORELIE', 'revenue': 1640000000.0, 'stock price ': 50.4},
 {'company name': 'HALEIGH', 'revenue': 2170000000.0, 'stock price ': 83.5},
 {'company name': 'MIKAELA', 'revenue': 6060000000.0, 'stock price ': 51.8},
 {'company name': 'MINNA', 'revenue': 618480000.0, 'stock price ': 55.9},
 {'company name': 'HERMINE', 'revenue': 192010000.0, 'stock price ': 65.5},
 {'company name': 'BORDEN', 'revenue': 8000000.0, 'stock price ': 60.2},
 {'company name': 'CART', 'revenue': nan, 'stock price ': 80.0},
 {'company name': 'KITTIE', 'revenue': 1040000000.0, 'stock price ': 73.7},
 {'company name': 'CASSEY', 'revenue': 2970000000.0, 'stock price ': 86.2},
 {'company name': 'ALEJANDRA', 'revenue': 2920000000.0, 'stock price ': 56.9}]
```